### DataSET Creation

In [2]:
%pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
     ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
     ---------------------------------------- 0.1/11.3 MB 2.0 MB/s eta 0:00:06
      --------------------------------------- 0.2/11.3 MB 3.1 MB/s eta 0:00:04
      --------------------------------------- 0.3/11.3 MB 2.0 MB/s eta 0:00:06
     - -------------------------------------- 0.3/11.3 MB 1.8 MB/s eta 0:00:07
     - -------------------------------------- 0.3/11.3 MB 1.7 MB/s eta 0:00:07
     - -------------------------------------- 0.3/11.3 MB 1.7 MB/s eta 0:00:07
     - -------------------------------------- 0.3/11.3 MB 1.7 MB/s eta 0:00:07
     - -------------------------------------- 0.3/11.3 MB 1.7 MB/s eta 0:00:07
     - -------------------------------------- 0.3/11.3 MB 1.7 MB/s eta 0:00:07
     - ------------------------------------- 0.3/11.3 MB 756.6 kB/s eta 0:00:15
     - ------------------------------------- 0.3/11.3 MB 756.6 kB/s eta 0:00:15
     - ------------------------------------- 0.3/11.3 MB 756.6 kB/s eta 0:00:15
     - ------------------------------------- 0.3/11.3 MB 756.6 kB/s eta 0:00:15
     - ------------------------------------- 0.3/11.3 MB 756.6 kB/s eta 0:00:15
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.3/11.3 MB 477.0 kB/s eta 0:00:24
     - ------------------------------------- 0.4/11.3 MB 269.9 kB/s eta 0:00:41
     - ------------------------------------- 0.4/11.3 MB 283.0 kB/s eta 0:00:39
     - ------------------------------------- 0.4/11.3 MB 294.7 kB/s eta 0:00:38
     - ------------------------------------- 0.4/11.3 MB 293.0 kB/s eta 0:00:38
     - ------------------------------------- 0.5/11.3 MB 324.4 kB/s eta 0:00:34
     - ------------------------------------- 0.6/11.3 MB 347.5 kB/s eta 0:00:32
     -- ------------------------------------ 0.6/11.3 MB 369.1 kB/s eta 0:00:30
     -- ------------------------------------ 0.6/11.3 MB 383.4 kB/s eta 0:00:28
     -- ------------------------------------ 0.7/11.3 MB 405.3 kB/s eta 0:00:27
     -- ------------------------------------ 0.7/11.3 MB 417.2 kB/s eta 0:00:26
     -- ------------------------------------ 0.7/11.3 MB 417.2 kB/s eta 0:00:26
     -- ------------------------------------ 0.7/11.3 MB 417.2 kB/s eta 0:00:26
     -- ------------------------------------ 0.7/11.3 MB 417.2 kB/s eta 0:00:26
     -- ------------------------------------ 0.7/11.3 MB 417.2 kB/s eta 0:00:26
     -- ------------------------------------ 0.8/11.3 MB 381.9 kB/s eta 0:00:28
     --- ----------------------------------- 0.9/11.3 MB 428.6 kB/s eta 0:00:25
     --- ----------------------------------- 0.9/11.3 MB 440.2 kB/s eta 0:00:24
     --- ----------------------------------- 0.9/11.3 MB 440.2 kB/s eta 0:00:24
     --- ----------------------------------- 0.9/11.3 MB 440.2 kB/s eta 0:00:24
     --- ----------------------------------- 0.9/11.3 MB 440.2 kB/s eta 0:00:24
     --- ----------------------------------- 0.9/11.3 MB 440.2 kB/s eta 0:00:24
     --- ----------------------------------- 0.9/11.3 MB 405.7 kB/s eta 0:00:26
     --- ----------------------------------- 1.0/11.3 MB 410.8 kB/s eta 0:00:26
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.0/11.3 MB 429.9 kB/s eta 0:00:24
     --- ----------------------------------- 1.1/11.3 MB 336.0 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 339.2 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 339.2 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 337.1 kB/s eta 0:00:31
     --- ----------------------------------- 1.1/11.3 MB 317.5 kB/s eta 0:00:33
     --- ----------------------------------- 1.1/11.3 MB 317.6 kB/s eta 0:00:33
     ---- ---------------------------------- 1.2/11.3 MB 322.0 kB/s eta 0:00:32
     ---- ---------------------------------- 1.2/11.3 MB 326.3 kB/s eta 0:00:32
     ---- ---------------------------------- 1.3/11.3 MB 338.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 342.8 kB/s eta 0:00:30
     ---- ---------------------------------- 1.3/11.3 MB 323.9 kB/s eta 0:00:31
     ---- ---------------------------------- 1.3/11.3 MB 326.4 kB/s eta 0:00:31
     ---- ---------------------------------- 1.4/11.3 MB 325.2 kB/s eta 0:00:31
     ---- ---------------------------------- 1.4/11.3 MB 328.9 kB/s eta 0:00:31
     ---- ---------------------------------- 1.4/11.3 MB 337.4 kB/s eta 0:00:30
     ----- --------------------------------- 1.5/11.3 MB 358.8 kB/s eta 0:00:28
     ----- --------------------------------- 1.6/11.3 MB 371.5 kB/s eta 0:00:27
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 379.2 kB/s eta 0:00:26
     ----- --------------------------------- 1.7/11.3 MB 332.8 kB/s eta 0:00:30
     ----- --------------------------------- 1.7/11.3 MB 332.8 kB/s eta 0:00:30
     ----- --------------------------------- 1.7/11.3 MB 330.7 kB/s eta 0:00:30
     ----- --------------------------------- 1.7/11.3 MB 329.7 kB/s eta 0:00:30
     ----- --------------------------------- 1.7/11.3 MB 329.7 kB/s eta 0:00:30
     ------ -------------------------------- 1.8/11.3 MB 331.6 kB/s eta 0:00:29
     ------ -------------------------------- 1.8/11.3 MB 331.6 kB/s eta 0:00:29
     ------ -------------------------------- 1.8/11.3 MB 331.6 kB/s eta 0:00:29
     ------ -------------------------------- 1.8/11.3 MB 331.6 kB/s eta 0:00:29
     ------ -------------------------------- 1.8/11.3 MB 331.6 kB/s eta 0:00:29
     ------ -------------------------------- 1.8/11.3 MB 318.4 kB/s eta 0:00:31
     ------ -------------------------------- 1.8/11.3 MB 321.2 kB/s eta 0:00:30
     ------ -------------------------------- 1.8/11.3 MB 325.9 kB/s eta 0:00:30
     ------ -------------------------------- 1.9/11.3 MB 330.4 kB/s eta 0:00:29
     ------ -------------------------------- 1.9/11.3 MB 340.3 kB/s eta 0:00:28
     ------ -------------------------------- 2.0/11.3 MB 343.8 kB/s eta 0:00:28
     ------ -------------------------------- 2.0/11.3 MB 343.6 kB/s eta 0:00:28
     ------ -------------------------------- 2.0/11.3 MB 347.1 kB/s eta 0:00:27
     ------- ------------------------------- 2.1/11.3 MB 357.3 kB/s eta 0:00:26
     ------- ------------------------------- 2.2/11.3 MB 364.1 kB/s eta 0:00:26
     ------- ------------------------------- 2.2/11.3 MB 367.2 kB/s eta 0:00:25
     ------- ------------------------------- 2.2/11.3 MB 367.2 kB/s eta 0:00:25
     ------- ------------------------------- 2.2/11.3 MB 367.2 kB/s eta 0:00:25
     ------- ------------------------------- 2.2/11.3 MB 367.2 kB/s eta 0:00:25
     ------- ------------------------------- 2.2/11.3 MB 367.2 kB/s eta 0:00:25
     ------- ------------------------------- 2.2/11.3 MB 357.5 kB/s eta 0:00:26
     ------- ------------------------------- 2.2/11.3 MB 357.5 kB/s eta 0:00:26
     ------- ------------------------------- 2.2/11.3 MB 355.4 kB/s eta 0:00:26
     ------- ------------------------------- 2.3/11.3 MB 358.5 kB/s eta 0:00:26
     ------- ------------------------------- 2.3/11.3 MB 359.0 kB/s eta 0:00:26
     -------- ------------------------------ 2.4/11.3 MB 369.9 kB/s eta 0:00:25
     -------- ------------------------------ 2.4/11.3 MB 372.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.4/11.3 MB 372.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.4/11.3 MB 372.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.4/11.3 MB 372.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.4/11.3 MB 372.9 kB/s eta 0:00:24
     -------- ------------------------------ 2.4/11.3 MB 362.9 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 364.1 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 365.4 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 363.6 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 363.3 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 363.3 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 362.3 kB/s eta 0:00:25
     -------- ------------------------------ 2.5/11.3 MB 362.0 kB/s eta 0:00:25
     -------- ------------------------------ 2.6/11.3 MB 361.7 kB/s eta 0:00:25
     -------- ------------------------------ 2.6/11.3 MB 360.7 kB/s eta 0:00:25
     -------- ------------------------------ 2.6/11.3 MB 361.2 kB/s eta 0:00:25
     --------- ----------------------------- 2.6/11.3 MB 363.2 kB/s eta 0:00:24
     --------- ----------------------------- 2.7/11.3 MB 362.9 kB/s eta 0:00:24
     --------- ----------------------------- 2.7/11.3 MB 365.5 kB/s eta 0:00:24
     --------- ----------------------------- 2.7/11.3 MB 371.5 kB/s eta 0:00:24
     --------- ----------------------------- 2.8/11.3 MB 380.2 kB/s eta 0:00:23
     --------- ----------------------------- 2.9/11.3 MB 384.7 kB/s eta 0:00:23
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     --------- ----------------------------- 2.9/11.3 MB 385.8 kB/s eta 0:00:22
     ---------- ---------------------------- 2.9/11.3 MB 366.3 kB/s eta 0:00:23
     ---------- ---------------------------- 3.0/11.3 MB 367.9 kB/s eta 0:00:23
     ---------- ---------------------------- 3.0/11.3 MB 369.6 kB/s eta 0:00:23
     ---------- ---------------------------- 3.1/11.3 MB 376.3 kB/s eta 0:00:23
     ---------- ---------------------------- 3.1/11.3 MB 381.7 kB/s eta 0:00:22
     ---------- ---------------------------- 3.2/11.3 MB 387.0 kB/s eta 0:00:22
     ----------- --------------------------- 3.2/11.3 MB 390.5 kB/s eta 0:00:21
     ----------- --------------------------- 3.2/11.3 MB 390.5 kB/s eta 0:00:21
     ----------- --------------------------- 3.2/11.3 MB 390.5 kB/s eta 0:00:21
     ----------- --------------------------- 3.2/11.3 MB 390.5 kB/s eta 0:00:21
     ----------- --------------------------- 3.2/11.3 MB 390.5 kB/s eta 0:00:21
     ----------- --------------------------- 3.3/11.3 MB 382.6 kB/s eta 0:00:22
     ----------- --------------------------- 3.3/11.3 MB 384.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.3/11.3 MB 388.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 390.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 390.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 390.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 390.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 390.1 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 381.0 kB/s eta 0:00:21
     ----------- --------------------------- 3.4/11.3 MB 368.9 kB/s eta 0:00:22
     ----------- --------------------------- 3.4/11.3 MB 368.9 kB/s eta 0:00:22
     ----------- --------------------------- 3.4/11.3 MB 369.1 kB/s eta 0:00:22
     ----------- --------------------------- 3.5/11.3 MB 372.8 kB/s eta 0:00:22
     ------------ -------------------------- 3.5/11.3 MB 372.5 kB/s eta 0:00:22
     ------------ -------------------------- 3.5/11.3 MB 373.9 kB/s eta 0:00:21
     ------------ -------------------------- 3.6/11.3 MB 378.5 kB/s eta 0:00:21
     ------------ -------------------------- 3.6/11.3 MB 379.9 kB/s eta 0:00:21
     ------------ -------------------------- 3.7/11.3 MB 386.1 kB/s eta 0:00:20
     ------------ -------------------------- 3.8/11.3 MB 390.7 kB/s eta 0:00:20
     ------------- ------------------------- 3.8/11.3 MB 393.4 kB/s eta 0:00:20
     ------------- ------------------------- 3.8/11.3 MB 393.4 kB/s eta 0:00:20
     ------------- ------------------------- 3.9/11.3 MB 395.5 kB/s eta 0:00:19
     ------------- ------------------------- 3.9/11.3 MB 401.4 kB/s eta 0:00:19
     ------------- ------------------------- 4.0/11.3 MB 405.3 kB/s eta 0:00:19
     ------------- ------------------------- 4.0/11.3 MB 407.5 kB/s eta 0:00:18
     -------------- ------------------------ 4.1/11.3 MB 410.1 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 415.4 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 418.2 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 418.2 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 418.2 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 418.2 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 418.2 kB/s eta 0:00:18
     -------------- ------------------------ 4.2/11.3 MB 412.0 kB/s eta 0:00:18
     -------------- ------------------------ 4.3/11.3 MB 413.7 kB/s eta 0:00:18
     -------------- ------------------------ 4.3/11.3 MB 414.8 kB/s eta 0:00:17
     -------------- ------------------------ 4.3/11.3 MB 414.9 kB/s eta 0:00:17
     -------------- ------------------------ 4.3/11.3 MB 414.6 kB/s eta 0:00:17
     --------------- ----------------------- 4.4/11.3 MB 416.4 kB/s eta 0:00:17
     --------------- ----------------------- 4.4/11.3 MB 416.4 kB/s eta 0:00:17
     --------------- ----------------------- 4.4/11.3 MB 415.7 kB/s eta 0:00:17
     --------------- ----------------------- 4.5/11.3 MB 419.2 kB/s eta 0:00:17
     --------------- ----------------------- 4.5/11.3 MB 421.6 kB/s eta 0:00:17
     --------------- ----------------------- 4.6/11.3 MB 424.5 kB/s eta 0:00:16
     --------------- ----------------------- 4.6/11.3 MB 428.4 kB/s eta 0:00:16
     --------------- ----------------------- 4.6/11.3 MB 430.3 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 428.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 431.0 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 431.0 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 431.0 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 431.0 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 431.0 kB/s eta 0:00:16
     ---------------- ---------------------- 4.7/11.3 MB 424.3 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16
     ---------------- ---------------------- 4.8/11.3 MB 424.1 kB/s eta 0:00:16

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import random
import pandas as pd

random.seed(42)

devices = ["phone", "tablet", "laptop", "smartwatch"]

battery_actions = [
    "drains quickly",
    "loses charge overnight",
    "drops from full charge within hours",
    "dies unexpectedly",
    "does not hold a charge",
    "gets hot while charging",
    "discharges while idle",
    "loses battery health rapidly",
    "powers off suddenly",
    "takes too long to charge"
]

battery_contexts = [
    "while gaming",
    "during video calls",
    "after a software update",
    "when using GPS",
    "during normal use",
    "while watching videos",
    "when connected to WiFi",
    "during standby",
    "while charging",
    "during online meetings"
]



hardware_parts = [
    "keyboard",
    "speaker",
    "microphone",
    "USB port",
    "charging port",
    "camera",
    "trackpad",
    "fingerprint sensor",
    "power button",
    "motherboard"
]

hardware_failures = [
    "stopped working",
    "works intermittently",
    "is not detected",
    "produces unusual behavior",
    "fails randomly",
    "became unresponsive",
    "is physically damaged",
    "disconnects frequently",
    "shows signs of failure",
    "malfunctions during use"
]


software_problems = [
    "apps keep crashing",
    "system freezes randomly",
    "device restarts unexpectedly",
    "operating system fails to boot",
    "software update failed",
    "WiFi disconnects frequently",
    "Bluetooth stops working",
    "device enters a boot loop",
    "screen freezes",
    "settings reset automatically"
]

software_contexts = [
    "after updating",
    "during startup",
    "while using multiple apps",
    "when opening settings",
    "during normal operation",
    "after installing new software",
    "when connected to the internet",
    "during file transfers",
    "after rebooting",
    "while charging"
]


screen_issues = [
    "screen flickers",
    "display shows vertical lines",
    "touchscreen is unresponsive",
    "brightness changes automatically",
    "screen goes black",
    "ghost touches occur",
    "screen freezes",
    "display shows distorted colors",
    "dead pixels appeared",
    "screen cracked"
]

screen_contexts = [
    "after a drop",
    "during normal use",
    "while charging",
    "after replacing the screen",
    "during gaming",
    "when using social media",
    "after an update",
    "during video playback",
    "when exposed to sunlight",
    "randomly throughout the day"
]


damage_events = [
    "fell into water",
    "was dropped on concrete",
    "was exposed to heavy rain",
    "had coffee spilled on it",
    "fell from a table",
    "was crushed inside a bag",
    "was left inside a hot car",
    "was dropped down stairs",
    "was exposed to beach sand",
    "was hit during a vehicle accident"
]

damage_results = [
    "and no longer turns on",
    "and the screen shattered",
    "and the touchscreen stopped working",
    "and charging no longer works",
    "and the speaker became distorted",
    "and random shutdowns started occurring",
    "and the display became damaged",
    "and internal components failed",
    "and the battery started overheating",
    "and several buttons stopped responding"
]


def generate_battery(n=400):
    items = []
    while len(items) < n:
        items.append(
            f"My {random.choice(devices)} {random.choice(battery_actions)} "
            f"{random.choice(battery_contexts)}."
        )
    return items


def generate_hardware(n=400):
    items = []
    while len(items) < n:
        items.append(
            f"The {random.choice(hardware_parts)} on my "
            f"{random.choice(devices)} {random.choice(hardware_failures)}."
        )
    return items


def generate_software(n=400):
    items = []
    while len(items) < n:
        items.append(
            f"My {random.choice(devices)} "
            f"{random.choice(software_problems)} "
            f"{random.choice(software_contexts)}."
        )
    return items


def generate_screen(n=400):
    items = []
    while len(items) < n:
        items.append(
            f"The {random.choice(screen_issues)} "
            f"{random.choice(screen_contexts)}."
        )
    return items


def generate_damage(n=400):
    items = []
    while len(items) < n:
        items.append(
            f"My {random.choice(devices)} "
            f"{random.choice(damage_events)} "
            f"{random.choice(damage_results)}."
        )
    return items


dataset = []

for x in generate_battery():
    dataset.append([x, "Battery degradation"])

for x in generate_hardware():
    dataset.append([x, "Hardware issue"])

for x in generate_software():
    dataset.append([x, "Software issue"])

for x in generate_screen():
    dataset.append([x, "Cracked screen"])

for x in generate_damage():
    dataset.append([x, "Water/Liquid damage"])

random.shuffle(dataset)

df = pd.DataFrame(dataset, columns=["issue", "label"])

print("Total rows:", len(df))
print(df.sample(10))

df.to_csv("device_issue_dataset_2000.csv", index=False)

Total rows: 2000
                                                  issue                label
469   My phone was dropped down stairs and no longer...  Water/Liquid damage
574   The display shows distorted colors during vide...       Cracked screen
463    The ghost touches occur when using social media.       Cracked screen
970   My smartwatch WiFi disconnects frequently duri...       Software issue
617       The camera on my laptop works intermittently.       Hardware issue
102   My phone device enters a boot loop after reboo...       Software issue
364   The microphone on my phone disconnects frequen...       Hardware issue
1412  The microphone on my smartwatch is physically ...       Hardware issue
1625  My phone loses charge overnight after a softwa...  Battery degradation
258   The touchscreen is unresponsive randomly throu...       Cracked screen

In [4]:
import pandas as pd

data = pd.read_csv(r"C:\Users\norud\Documents\DevOps_Proj\CPE028_Project\ml\datasets\Data_processing\device_issue_dataset_2000.csv")

In [5]:
to_label = data['issue']

In [10]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
     ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
     ---------------------------------------- 0.1/8.9 MB 2.9 MB/s eta 0:00:04
      --------------------------------------- 0.2/8.9 MB 2.3 MB/s eta 0:00:04
      --------------------------------------- 0.2/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.2/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 1.3 MB/s eta 0:00:07
     - -------------------------------------- 0.3/8.9 MB 655.2 kB/s eta 0:00:14
     - -------------------------------------- 0.3/8.9 MB 655.2 kB/s eta 0:00:14
     - -------------------------------------- 0.3/8.9 MB 655.2 kB/s eta 0:00:14
     - -------------------------------------- 0.3/8.9 MB 655.2 kB/s eta 0:00:14
     - -------------------------------------- 0.3/8.9 MB 655.2 kB/s eta 0:00:14
     - -------------------------------------- 0.3/8.9 MB 457.1 kB/s eta 0:00:19
     - -------------------------------------- 0.3/8.9 MB 457.1 kB/s eta 0:00:19
     - -------------------------------------- 0.3/8.9 MB 457.1 kB/s eta 0:00:19
     - -------------------------------------- 0.3/8.9 MB 457.1 kB/s eta 0:00:19
     - -------------------------------------- 0.3/8.9 MB 457.1 kB/s eta 0:00:19
     - -------------------------------------- 0.3/8.9 MB 361.3 kB/s eta 0:00:24
     - -------------------------------------- 0.3/8.9 MB 360.3 kB/s eta 0:00:24
     - -------------------------------------- 0.3/8.9 MB 360.3 kB/s eta 0:00:24
     - -------------------------------------- 0.3/8.9 MB 360.3 kB/s eta 0:00:24
     - -------------------------------------- 0.3/8.9 MB 360.3 kB/s eta 0:00:24
     - -------------------------------------- 0.3/8.9 MB 360.3 kB/s eta 0:00:24
     - -------------------------------------- 0.4/8.9 MB 314.7 kB/s eta 0:00:28
     - -------------------------------------- 0.4/8.9 MB 331.7 kB/s eta 0:00:26
     -- ------------------------------------- 0.5/8.9 MB 343.5 kB/s eta 0:00:25
     -- ------------------------------------- 0.5/8.9 MB 351.0 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 357.5 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 352.9 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.5/8.9 MB 359.2 kB/s eta 0:00:24
     -- ------------------------------------- 0.6/8.9 MB 312.8 kB/s eta 0:00:27
     -- ------------------------------------- 0.6/8.9 MB 310.3 kB/s eta 0:00:27
     -- ------------------------------------- 0.6/8.9 MB 311.0 kB/s eta 0:00:27
     -- ------------------------------------- 0.6/8.9 MB 316.8 kB/s eta 0:00:27
     -- ------------------------------------- 0.6/8.9 MB 325.0 kB/s eta 0:00:26
     -- ------------------------------------- 0.7/8.9 MB 327.7 kB/s eta 0:00:26
     -- ------------------------------------- 0.7/8.9 MB 327.7 kB/s eta 0:00:26
     --- ------------------------------------ 0.7/8.9 MB 330.0 kB/s eta 0:00:25
     --- ------------------------------------ 0.8/8.9 MB 358.7 kB/s eta 0:00:23
     --- ------------------------------------ 0.8/8.9 MB 367.7 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 380.3 kB/s eta 0:00:22
     --- ------------------------------------ 0.9/8.9 MB 320.1 kB/s eta 0:00:26
     ---- ----------------------------------- 0.9/8.9 MB 320.2 kB/s eta 0:00:25
     ---- ----------------------------------- 0.9/8.9 MB 320.2 kB/s eta 0:00:25
     ---- ----------------------------------- 0.9/8.9 MB 320.2 kB/s eta 0:00:25
     ---- ----------------------------------- 0.9/8.9 MB 320.2 kB/s eta 0:00:25
     ---- ----------------------------------- 0.9/8.9 MB 320.2 kB/s eta 0:00:25
     ---- ----------------------------------- 0.9/8.9 MB 300.4 kB/s eta 0:00:27
     ---- ----------------------------------- 0.9/8.9 MB 300.4 kB/s eta 0:00:27
     ---- ----------------------------------- 0.9/8.9 MB 300.4 kB/s eta 0:00:27
     ---- ----------------------------------- 0.9/8.9 MB 300.4 kB/s eta 0:00:27
     ---- ----------------------------------- 0.9/8.9 MB 300.4 kB/s eta 0:00:27
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 0.9/8.9 MB 286.7 kB/s eta 0:00:28
     ---- ----------------------------------- 1.0/8.9 MB 237.1 kB/s eta 0:00:34
     ---- ----------------------------------- 1.0/8.9 MB 236.9 kB/s eta 0:00:34
     ---- ----------------------------------- 1.0/8.9 MB 241.7 kB/s eta 0:00:33
     ---- ----------------------------------- 1.0/8.9 MB 244.8 kB/s eta 0:00:33
     ---- ----------------------------------- 1.1/8.9 MB 248.4 kB/s eta 0:00:32
     ---- ----------------------------------- 1.1/8.9 MB 252.4 kB/s eta 0:00:31
     ---- ----------------------------------- 1.1/8.9 MB 255.0 kB/s eta 0:00:31
     ----- ---------------------------------- 1.2/8.9 MB 264.0 kB/s eta 0:00:30
     ----- ---------------------------------- 1.2/8.9 MB 272.8 kB/s eta 0:00:29
     ----- ---------------------------------- 1.2/8.9 MB 279.2 kB/s eta 0:00:28
     ----- ---------------------------------- 1.3/8.9 MB 287.7 kB/s eta 0:00:27
     ----- ---------------------------------- 1.3/8.9 MB 291.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 298.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 298.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 298.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 298.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 298.5 kB/s eta 0:00:26
     ------ --------------------------------- 1.4/8.9 MB 286.0 kB/s eta 0:00:27
     ------ --------------------------------- 1.4/8.9 MB 289.6 kB/s eta 0:00:26
     ------ --------------------------------- 1.5/8.9 MB 294.2 kB/s eta 0:00:26
     ------ --------------------------------- 1.5/8.9 MB 298.6 kB/s eta 0:00:25
     ------ --------------------------------- 1.5/8.9 MB 301.1 kB/s eta 0:00:25
     ------- -------------------------------- 1.6/8.9 MB 309.3 kB/s eta 0:00:24
     ------- -------------------------------- 1.6/8.9 MB 309.3 kB/s eta 0:00:24
     ------- -------------------------------- 1.6/8.9 MB 309.3 kB/s eta 0:00:24
     ------- -------------------------------- 1.6/8.9 MB 309.3 kB/s eta 0:00:24
     ------- -------------------------------- 1.6/8.9 MB 309.3 kB/s eta 0:00:24
     ------- -------------------------------- 1.6/8.9 MB 296.6 kB/s eta 0:00:25
     ------- -------------------------------- 1.6/8.9 MB 302.6 kB/s eta 0:00:25
     ------- -------------------------------- 1.7/8.9 MB 307.6 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 307.6 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 307.6 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 307.6 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 307.6 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 302.0 kB/s eta 0:00:24
     ------- -------------------------------- 1.7/8.9 MB 305.0 kB/s eta 0:00:24
     ------- -------------------------------- 1.8/8.9 MB 307.8 kB/s eta 0:00:24
     ------- -------------------------------- 1.8/8.9 MB 307.8 kB/s eta 0:00:24
     ------- -------------------------------- 1.8/8.9 MB 307.8 kB/s eta 0:00:24
     ------- -------------------------------- 1.8/8.9 MB 307.8 kB/s eta 0:00:24
     ------- -------------------------------- 1.8/8.9 MB 307.8 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 299.1 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 301.1 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.8/8.9 MB 303.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 292.2 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 291.6 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 291.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 291.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 291.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 291.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 291.9 kB/s eta 0:00:24
     -------- ------------------------------- 1.9/8.9 MB 281.9 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 283.7 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 286.0 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 286.0 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 286.0 kB/s eta 0:00:25
     -------- ------------------------------- 1.9/8.9 MB 286.0 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 277.9 kB/s eta 0:00:25
     -------- ------------------------------- 2.0/8.9 MB 255.0 kB/s eta 0:00:28
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 256.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.0/8.9 MB 251.5 kB/s eta 0:00:28
     --------- ------------------------------ 2.1/8.9 MB 253.8 kB/s eta 0:00:27
     --------- ------------------------------ 2.1/8.9 MB 258.1 kB/s eta 0:00:27
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.1/8.9 MB 259.6 kB/s eta 0:00:26
     --------- ------------------------------ 2.2/8.9 MB 241.6 kB/s eta 0:00:28
     --------- ------------------------------ 2.2/8.9 MB 243.0 kB/s eta 0:00:28
     --------- ------------------------------ 2.2/8.9 MB 244.7 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.5 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.5 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.5 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.5 kB/s eta 0:00:28
     ---------- ----------------------------- 2.2/8.9 MB 246.5 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 244.2 kB/s eta 0:00:28
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 228.7 kB/s eta 0:00:29
     ---------- ----------------------------- 2.3/8.9 MB 224.1 kB/s eta 0:00:30
     ---------- ----------------------------- 2.3/8.9 MB 224.1 kB/s eta 0:00:30
     ---------- ----------------------------- 2.3/8.9 MB 223.1 kB/s eta 0:00:30
     ---------- ----------------------------- 2.3/8.9 MB 223.7 kB/s eta 0:00:30
     ---------- ----------------------------- 2.4/8.9 MB 226.9 kB/s eta 0:00:29
     ---------- ----------------------------- 2.4/8.9 MB 229.2 kB/s eta 0:00:29
     ----------- ---------------------------- 2.4/8.9 MB 231.4 kB/s eta 0:00:28
     ----------- ---------------------------- 2.4/8.9 MB 231.4 kB/s eta 0:00:28
     ----------- ---------------------------- 2.4/8.9 MB 231.4 kB/s eta 0:00:28
     ----------- ---------------------------- 2.4/8.9 MB 231.4 kB/s eta 0:00:28
     ----------- ---------------------------- 2.4/8.9 MB 231.4 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 229.5 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 232.6 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 232.6 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 232.6 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 232.6 kB/s eta 0:00:28
     ----------- ---------------------------- 2.5/8.9 MB 232.6 kB/s eta 0:00:28
     ----------- ---------------------------- 2.6/8.9 MB 230.1 kB/s eta 0:00:28
     ----------- ---------------------------- 2.6/8.9 MB 234.1 kB/s eta 0:00:27
     ----------- ---------------------------- 2.6/8.9 MB 235.3 kB/s eta 0:00:27
     ------------ --------------------------- 2.7/8.9 MB 238.5 kB/s eta 0:00:27
     ------------ --------------------------- 2.7/8.9 MB 241.5 kB/s eta 0:00:26
     ------------ --------------------------- 2.7/8.9 MB 241.5 kB/s eta 0:00:26
     ------------ --------------------------- 2.7/8.9 MB 241.5 kB/s eta 0:00:26
     ------------ --------------------------- 2.7/8.9 MB 241.5 kB/s eta 0:00:26
     ------------ --------------------------- 2.7/8.9 MB 241.5 kB/s eta 0:00:26
     ------------ --------------------------- 2.8/8.9 MB 240.2 kB/s eta 0:00:26
     ------------ --------------------------- 2.8/8.9 MB 240.2 kB/s eta 0:00:26
     ------------ --------------------------- 2.8/8.9 MB 240.9 kB/s eta 0:00:26
     ------------ --------------------------- 2.8/8.9 MB 244.0 kB/s eta 0:00:25

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
%pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ----- ---------------------------------- 0.2/1.6 MB 5.9 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------ --------------------------------- 0.3/1.6 MB 3.2 MB/s eta 0:00:01
     ------- -------------------------------- 0.3/1.6 MB 376.7 kB/s eta 0:00:04
     --------- ------------------------------ 0.4/1.6 MB 437.4 kB/s eta 0:00:03
     --------- ------------------------------ 0.4/1.6 MB 432.9 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ---------- ----------------------------- 0.4/1.6 MB 453.0 kB/s eta 0:00:03
     ------------ --------------------------- 0.5/1.6 MB 402.3 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     -------------- ------------------------- 0.6/1.6 MB 459.6 kB/s eta 0:00:03
     --------------- ------------------------ 0.6/1.6 MB 319.5 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.7 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ---------------- ----------------------- 0.6/1.6 MB 327.8 kB/s eta 0:00:03
     ----------------- ---------------------- 0.7/1.6 MB 295.5 kB/s eta 0:00:04
     ----------------- ---------------------- 0.7/1.6 MB 300.8 kB/s eta 0:00:03
     ------------------- -------------------- 0.7/1.6 MB 316.7 kB/s eta 0:00:03
     ------------------- -------------------- 0.8/1.6 MB 321.2 kB/s eta 0:00:03
     -------------------- ------------------- 0.8/1.6 MB 327.7 kB/s eta 0:00:03
     --------------------- ------------------ 0.8/1.6 MB 338.0 kB/s eta 0:00:03
     ---------------------- ----------------- 0.9/1.6 MB 346.1 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ----------------------- ---------------- 0.9/1.6 MB 351.7 kB/s eta 0:00:02
     ------------------------ --------------- 0.9/1.6 MB 322.4 kB/s eta 0:00:02
     ------------------------ --------------- 0.9/1.6 MB 317.3 kB/s eta 0:00:02
     ------------------------ --------------- 0.9/1.6 MB 317.3 kB/s eta 0:00:02
     ------------------------- -------------- 1.0/1.6 MB 317.6 kB/s eta 0:00:02
     ------------------------- -------------- 1.0/1.6 MB 319.4 kB/s eta 0:00:02
     --------------------------- ------------ 1.1/1.6 MB 336.0 kB/s eta 0:00:02
     ---------------------------- ----------- 1.1/1.6 MB 347.2 kB/s eta 0:00:02
     ---------------------------- ----------- 1.1/1.6 MB 347.2 kB/s eta 0:00:02
     ---------------------------- ----------- 1.1/1.6 MB 347.2 kB/s eta 0:00:02
     ---------------------------- ----------- 1.1/1.6 MB 347.2 kB/s eta 0:00:02
     ---------------------------- ----------- 1.1/1.6 MB 347.2 kB/s eta 0:00:02
     ----------------------------- ---------- 1.1/1.6 MB 327.7 kB/s eta 0:00:02
     ----------------------------- ---------- 1.2/1.6 MB 332.1 kB/s eta 0:00:02
     ------------------------------ --------- 1.2/1.6 MB 338.0 kB/s eta 0:00:02
     ------------------------------ --------- 1.2/1.6 MB 338.0 kB/s eta 0:00:02
     ------------------------------ --------- 1.2/1.6 MB 338.0 kB/s eta 0:00:02
     ------------------------------ --------- 1.2/1.6 MB 338.0 kB/s eta 0:00:02
     ------------------------------ --------- 1.2/1.6 MB 338.0 kB/s eta 0:00:02
     ------------------------------- -------- 1.2/1.6 MB 322.2 kB/s eta 0:00:02
     ------------------------------- -------- 1.2/1.6 MB 326.4 kB/s eta 0:00:01
     -------------------------------- ------- 1.3/1.6 MB 330.4 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 339.7 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.3/1.6 MB 342.2 kB/s eta 0:00:01
     ---------------------------------- ----- 1.4/1.6 MB 320.4 kB/s eta 0:00:01
     ----------------------------------- ---- 1.4/1.6 MB 324.1 kB/s eta 0:00:01
     ------------------------------------- -- 1.5/1.6 MB 336.1 kB/s eta 0:00:01
     -------------------------------------- - 1.5/1.6 MB 340.7 kB/s eta 0:00:01
     ---------------------------------------  1.5/1.6 MB 348.7 kB/s eta 0:00:01
     ---------------------------------------- 1.6/1.6 MB 348.8 kB/s eta 0:00:00
Requirement already satisfied: tqdm in c:\users\norud\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.68.1)
Requirement already satisfied: click in c:\users\norud\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.4.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\norud\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2026.5.9)
Requirement already satisfied: joblib in c:\users\norud\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: colorama in c:\users\norud\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Installing collected packages: nltk
Successfully installed nltk-3.9.4
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
import re
import nltk
from sklearn.feature_extraction.text import CountVectorizer

nltk.download('punkt')

def categorize_issue_text(issue_description):
    issue_description = issue_description.lower()

    if re.search(r'battery|charge|drains|loses charge|dies|hot while charging|discharges', issue_description):
        return "Battery degradation"
    if re.search(r'keyboard|speaker|microphone|usb port|charging port|camera|trackpad|fingerprint sensor|power button|motherboard|stopped working|intermittently|not detected|malfunctions|hardware', issue_description):
        return "Hardware issue"
    if re.search(r'apps crashing|system freezes|restarts unexpectedly|fails to boot|update failed|wifi disconnects|bluetooth stops|boot loop|screen freezes|settings reset|software|os|operating system', issue_description):
        return "Software issue"
    if re.search(r'screen|display|flickers|lines|unresponsive|black screen|ghost touches|distorted colors|dead pixels|cracked', issue_description):
        return "Cracked screen"
    if re.search(r'water|spilled|liquid|dropped on concrete|exposed to rain|fell from table|crushed|hot car|dropped down stairs|beach sand|hit during accident', issue_description):
        return "Water/Liquid damage"
    return "Unknown"

categorized_to_label = to_label.apply(categorize_issue_text)

print("Original 'to_label' (sample):")
print(to_label.head())
print("\nCategorized 'to_label' (sample):")
print(categorized_to_label.head())
print("\nValue counts of categorized 'to_label':")
print(categorized_to_label.value_counts())

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\norud\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

Original 'to_label' (sample):
0      The screen flickers after replacing the screen.
1    My tablet was hit during a vehicle accident an...
2    My tablet was dropped down stairs and internal...
3     My laptop loses charge overnight when using GPS.
4    My laptop was crushed inside a bag and the bat...
Name: issue, dtype: object

Categorized 'to_label' (sample):
0         Cracked screen
1         Hardware issue
2    Water/Liquid damage
3    Battery degradation
4    Battery degradation
Name: issue, dtype: object

Value counts of categorized 'to_label':
issue
Software issue         551
Hardware issue         477
Battery degradation    416
Cracked screen         321
Water/Liquid damage    121
Unknown                114
Name: count, dtype: int64

In [16]:
data['predicted_label'] = categorized_to_label

print("DataFrame with 'predicted_label' column:")
display(data.head())

DataFrame with 'predicted_label' column:

,issue,label,predicted_label
0,The screen flickers after replacing the screen.,Cracked screen,Cracked screen
1,My tablet was hit during a vehicle accident an...,Water/Liquid damage,Hardware issue
2,My tablet was dropped down stairs and internal...,Water/Liquid damage,Water/Liquid damage
3,My laptop loses charge overnight when using GPS.,Battery degradation,Battery degradation
4,My laptop was crushed inside a bag and the bat...,Water/Liquid damage,Battery degradation

In [17]:
data = data[['issue', 'predicted_label']]
print("DataFrame after dropping 'label' column:")
display(data.head())

DataFrame after dropping 'label' column:

                                               issue      predicted_label
0    The screen flickers after replacing the screen.       Cracked screen
1  My tablet was hit during a vehicle accident an...       Hardware issue
2  My tablet was dropped down stairs and internal...  Water/Liquid damage
3   My laptop loses charge overnight when using GPS.  Battery degradation
4  My laptop was crushed inside a bag and the bat...  Battery degradation

In [18]:
data.to_csv("final_dataset.csv", index=False)
print("Updated dataset saved to 'final_dataset.csv'")

Updated dataset saved to 'final_dataset.csv'

### repairability index scores

In [19]:
french_repairability = pd.read_csv(r"C:\Users\norud\Documents\DevOps_Proj\CPE028_Project\ml\datasets\repairability-final.csv")
iFixit_repairability = pd.read_csv(r"C:\Users\norud\Documents\DevOps_Proj\CPE028_Project\ml\datasets\iFixit Repairability Scores (Public) - Smartphones.csv")

In [20]:
display(french_repairability.head())
print()
display(iFixit_repairability.head())

,Image,Brand,Model,Category,Page,Img Score,Vision Score
0,https://www.indicereparabilite.fr/wp-content/u...,KXD,KXD D58,Smartphones,3,NaN,1.0
1,https://www.indicereparabilite.fr/wp-content/u...,HONOR,STK-LX1,Smartphones,3,NaN,6.5
2,https://www.indicereparabilite.fr/wp-content/u...,SAMSUNG,SM-A105F,Smartphones,3,NaN,5.7
3,https://www.indicereparabilite.fr/wp-content/u...,HHuawei P smart Z,STK-LX1,Smartphones,3,NaN,5.5
4,https://www.indicereparabilite.fr/wp-content/u...,XIAOMI,Mi 9 Lite (128 Go),Smartphones,3,NaN,7.0

,Release Order,OEM,Device,Date,Summary,Score,Note,Scorecard Version
0,155,Google,Pixel 9,2024,"+ Screen repairs are prioritized, and all othe...",5,NaN,2.0
1,154,Google,Pixel 9 Pro,2024,"+ Screen repairs are prioritized, and all othe...",5,NaN,2.0
2,153,Google,Pixel 9 Pro XL,2024,"+ Screen repairs are prioritized, and all othe...",5,NaN,2.0
3,152,Google,Pixel 9 Pro Fold,2024,+ Getting repairs started is easier thanks to ...,4,NaN,2.0
4,151,Apple,iPhone 16,2024,+ Great design prioritizes screen repairs whil...,7,NaN,1.9

In [21]:
french_repairability.info()
print("\n\n")
iFixit_repairability.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 865 entries, 0 to 864
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Image         865 non-null    object
 1   Brand         865 non-null    object
 2   Model         864 non-null    object
 3   Category      865 non-null    object
 4   Page          865 non-null    int64
 5   Img Score     0 non-null      float64
 6   Vision Score  865 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 47.4+ KB



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release Order      155 non-null    int64
 1   OEM                155 non-null    object
 2   Device             155 non-null    object
 3   Date               155 non-null    int64
 4   Summary            155 non-null    object
 5   Score              155 non-null    int64
 6   Note               9 non-null      object
 7   Scorecard Version  155 non-null    float64
dtypes: float64(1), int64(3), object(4)
memory usage: 9.8+ KB

In [ ]:
print(iFixit_repairability.columns.to_list())
print(french_repairability.columns.to_list())

['Release Order', 'OEM', 'Device', 'Date', 'Summary', 'Score', 'Note', 'Scorecard Version']
['Image', 'Brand', 'Model', 'Category', 'Page', 'Img Score', 'Vision Score']

In [ ]:
iFixit_repairability.Device

0                      Pixel 9
1                  Pixel 9 Pro
2               Pixel 9 Pro XL
3             Pixel 9 Pro Fold
4                    iPhone 16
                ...
150                   Surround
151                         N8
152                 iPhone 3GS
153                  iPhone 3G
154    iPhone (1st Generation)
Name: Device, Length: 155, dtype: object

In [ ]:
# Prepare french_repairability DataFrame
df_french_prep = french_repairability.rename(columns={
    'Brand': 'Manufacturer',
    'Model': 'Product_Model',
    'Category': 'Category_Type',
    'Vision Score': 'Repairability_Score'
})
df_french_prep = df_french_prep[['Manufacturer', 'Product_Model', 'Category_Type', 'Repairability_Score']]

# Prepare iFixit_repairability DataFrame
df_ifixit_prep = iFixit_repairability.rename(columns={
    'OEM': 'Manufacturer',
    'Device': 'Product_Model',
    'Score': 'Repairability_Score',
    'Summary': 'Summary_Description',
    'Scorecard Version': 'Scorecard_Version'
})
df_ifixit_prep = df_ifixit_prep[['Manufacturer', 'Product_Model', 'Repairability_Score', 'Summary_Description', 'Scorecard_Version']]

# Concatenate the prepared DataFrames to create a unified repairability dataset
final_repairablity = pd.concat([df_french_prep, df_ifixit_prep], ignore_index=True, sort=False)
final_repairablity

,Manufacturer,Product_Model,Category_Type,Repairability_Score,Summary_Description,Scorecard_Version
0,KXD,KXD D58,Smartphones,1.0,NaN,NaN
1,HONOR,STK-LX1,Smartphones,6.5,NaN,NaN
2,SAMSUNG,SM-A105F,Smartphones,5.7,NaN,NaN
3,HHuawei P smart Z,STK-LX1,Smartphones,5.5,NaN,NaN
4,XIAOMI,Mi 9 Lite (128 Go),Smartphones,7.0,NaN,NaN
...,...,...,...,...,...,...
1015,HTC,Surround,NaN,5.0,+ Relatively easy to remove the rear case to r...,1.0
1016,Nokia,N8,NaN,8.0,"+ The battery, although considered by Nokia no...",1.0
1017,Apple,iPhone 3GS,NaN,7.0,+ LCD and front glass are not fused and can be...,1.0
1018,Apple,iPhone 3G,NaN,7.0,+ LCD and front glass are not fused and can be...,1.0
1019,Apple,iPhone (1st Generation),NaN,2.0,+ Standard Phillips screws used throughout.\n-...,1.0

In [ ]:
list(final_repairablity[final_repairablity.Manufacturer != "NaN"].Manufacturer.unique())

['KXD',
 'HONOR',
 'SAMSUNG',
 'HHuawei P smart Z',
 'XIAOMI',
 'Huawei Y6 2018',
 'Huawei P smart Z',
 'LOGICOM',
 'Wiko',
 'Huawei P40 Pro',
 'Huawei Mate20 lite',
 'WIKO SAS',
 'Huawei P30 Pro',
 'NEVA LEAF',
 'APPLE',
 'Huawei P20 lite',
 'OnePlus',
 'HMD GLOBAL OY',
 'ASUS',
 'Huawei P40',
 'Samsung',
 'YANG TECHNOLOGY SAS',
 'Huawei P40 lite',
 'Huawei P30',
 'Maxcom',
 'MOTOROLA',
 'Huawei',
 'Huawei Y6p',
 'Huawei nova 5T',
 'ATHESI',
 'QILIVE',
 'SPECTRALINK',
 'Google',
 'Kapsys',
 'Fairphone',
 'CORSAIR',
 'WHY!',
 'FRAMEWORK',
 'RAZER',
 'RAZEN',
 'MICROSOFT',
 'MAIBENBEN',
 'KUU',
 'LENOVO',
 'MECHREVO',
 'SELECLINE',
 '07/12/2021',
 '600081701',
 'PHILIPS',
 '–',
 '55NANO796NE',
 '43UP75006LF',
 'Smart Tech',
 'SMARTTECH',
 '32T4302',
 '55GX3',
 '65GX3',
 'SONY',
 '75NANO903',
 'OLED55BX6LB',
 '?',
 'Hisense',
 'OLED65BX6LB',
 '55NANO793NE',
 '82UN85006LA',
 'TCL',
 '65NANO796NE',
 '43UN71003',
 '55UN74003LB',
 'TOSHIBA',
 '55CX6',
 'HUSQVARNA',
 'GARDEN TECHNIC',
 'BOSCH',
 'ROBOMOW',
 'GARDENA',
 'WORX',
 'GREENWORKS',
 'MCCULLOCH',
 'Landxcape',
 'WOLF',
 'OPPO',
 'Swissvoice',
 'Huawei P20',
 'DORO',
 'Huawei Mate40 Pro',
 'Samsung Electronics Co. Ltd',
 'Huawei Y6s',
 'HONOR 9A',
 'GENERIQUE',
 'Huawei Y7 2019',
 'Huawei P smart 2019',
 'Huawei P smart 2020',
 'VIVO',
 'Huawei P smart+',
 'Huawei Y7 2018',
 'Huawei P40 Pro+',
 'Huawei P smart 2021',
 'Huawei P smart S',
 'Apple',
 'Huawei Mate20 Pro',
 'Huawei Y5p',
 'Apple Distribution International',
 'VOG-L29',
 'HUAWEI P40',
 'OnePlus 8',
 'CROSSCALL',
 '19 janvier 2021',
 'ONEPLUS',
 'SAMSUNG Galaxy A72 4G Blanc',
 'Huawei Mate30 Pro',
 'Huawei Mate20',
 'EssentielB',
 'Nautiz',
 'POLAROID',
 'CONTINENTAL EDISON',
 'CHIQ',
 'OLED65CX6LA',
 '43UN73006',
 'LG',
 'HISENSE',
 '17/12/2020',
 'Panasonic',
 'HMD',
 'Nokia',
 'Mi',
 'Microsoft',
 'Motorola',
 'Shift',
 'Essential',
 'Sony',
 'Moto',
 'Asus',
 'Meizu',
 'Vivo',
 'Xiaomi',
 'Oppo',
 'Lenovo',
 'Nexus',
 'HTC',
 'Amazon',
 'BlackBerry']

In [ ]:
final_repairablity.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         1020 non-null   object
 1   Product_Model        1019 non-null   object
 2   Category_Type        865 non-null    object
 3   Repairability_Score  1020 non-null   float64
 4   Summary_Description  155 non-null    object
 5   Scorecard_Version    155 non-null    float64
dtypes: float64(2), object(4)
memory usage: 47.9+ KB

In [25]:
fr = french_repairability[['Brand', 'Model', 'Category',"Vision Score"]]
fr

                 Brand               Model     Category  Vision Score
0                  KXD             KXD D58  Smartphones           1.0
1                HONOR             STK-LX1  Smartphones           6.5
2              SAMSUNG            SM-A105F  Smartphones           5.7
3    HHuawei P smart Z             STK-LX1  Smartphones           5.5
4               XIAOMI  Mi 9 Lite (128 Go)  Smartphones           7.0
..                 ...                 ...          ...           ...
860            Hisense             55U82QF           TV           6.8
861            SAMSUNG       QE85Q80TATXXC           TV           7.2
862            SAMSUNG      UE32T4005AKXXC           TV           5.7
863            SAMSUNG      UE75TU7125KXXC           TV           6.1
864            SAMSUNG       QE75Q95TATXXC           TV           7.0

[865 rows x 4 columns]